const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const tracks=[
['aurora-dream','Aurora Dream','AURA Originals','Dream Pop','assets/audio/aurora-dream.mp3'],['idhu-territory','Idhu Enga Territory','Sai Abhyankkar','Tamil','assets/audio/idhu-enga-territory.mp3'],['midnight-rain','Midnight Rain','AURA Originals','Ambient','assets/audio/midnight-rain.mp3'],['neon-drive','Neon Drive','AURA Originals','Synthwave','assets/audio/neon-drive.mp3'],['ooroda','Ooroda Oththa Don','Sai Abhyankkar','Tamil','assets/audio/ooroda-oththa-don.mp3'],['solar','Solar Pulse','AURA Originals','Electronic','assets/audio/solar-pulse.mp3'],['thatak','Thatak Junak Arrival Dream','Sai Abhyankkar','Tamil BGM','assets/audio/thatak-junak-arrival-dream.mp3'],['verappa-f','Verappa (Urumum Venga) - Female Version','Sai Abhyankkar','Tamil BGM','assets/audio/verappa-urumum-venga-female.mp3'],['verappa-i','Verappa Thandavam Interval','Sai Abhyankkar','Tamil BGM','assets/audio/verappa-thandavam-interval.mp3']].map(x=>({id:x[0],title:x[1],artist:x[2],genre:x[3],src:x[4]}));
const state={view:'home',q:'',track:null,index:-1,playing:false,theme:localStorage.aura13theme||'dark',project:{name:'Untitled AURA Project',bpm:120,clips:[],automation:[{x:18,y:55},{x:42,y:35},{x:67,y:72},{x:88,y:45}]},selectedClip:null,autosave:null};
const audio=$('#audio'); let ctx,source,gain,analyser,raf;
function toast(s){const t=$('#toast');t.textContent=s;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),1700)}
function fmt(s){s=Number(s)||0;return `${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function card(t){return `<div class="card" data-track="${t.id}"><div class="cover">A</div><h3>${esc(t.title)}</h3><p>${esc(t.artist)}</p></div>`}
function row(t,i){return `<div class="track" data-track="${t.id}"><span>${i+1}</span><div class="mini">A</div><div class="track-main"><strong>${esc(t.title)}</strong><span>${esc(t.artist)}</span></div><span class="track-meta">${esc(t.genre)}</span><span class="track-time">Play</span></div>`}
function home(){let ts=filtered();return `<div class="hero"><div class="hero-card"><div class="tag">AURA V13 • NEXUS DAW</div><h1>Listen.<br>Edit.<br>Create.</h1><p class="muted">A local-first music platform that blends a premium player with a visual arranger, remix workflow, sample slicer and project studio.</p><div class="actions"><button class="primary" data-action="play-all">▶ Play library</button><button class="secondary" data-view="arranger">Open Arranger</button></div></div><div class="feature"><div class="tag">V13 CREATOR ENGINE</div><h2>Music, arranged your way.</h2><p class="muted">Beat snapping, draggable clips, automation points, per-clip controls, sample slicing and autosaved projects.</p><div class="row"><span class="pill">Beat Snap</span><span class="pill">Automation</span><span class="pill">8 Slices</span><span class="pill">Autosave</span></div></div></div><div class="section"><div class="section-head"><h2>Your music</h2><span class="muted">${ts.length} tracks</span></div><div class="cards">${ts.slice(0,8).map(card).join('')}</div></div><div class="section"><div class="section-head"><h2>Library</h2><button class="tool" data-view="library">Open full library</button></div><div class="tracklist">${ts.slice(0,12).map(row).join('')}</div></div>`}
function library(){const ts=filtered();return `<div class="section-head"><h2>Library</h2><button class="primary" data-action="import">＋ Add music</button></div><div class="tracklist">${ts.map(row).join('')||'<div class="empty">No matching music.</div>'}</div>`}
function arranger(){const p=state.project;const clips=p.clips.length?p.clips:[{id:'demo',trackId:tracks[0].id,start:8,dur:18,gain:1}];return `<div class="section-head"><div><div class="tag">ARRANGER • V13</div><h2>Visual Timeline</h2><span class="muted">Drag clips • snap to beats • double click to add automation</span></div><div class="row"><button class="tool" data-action="add-clip">＋ Clip</button><button class="tool" data-action="snap">Snap ${p.snap?'ON':'OFF'}</button><button class="tool" data-action="save">💾 Save</button></div></div><div class="studio-grid"><div class="studio-card"><div class="toolbar"><button class="tool" data-action="zoom-out">−</button><button class="tool">Zoom ${p.zoom||100}%</button><button class="tool" data-action="zoom-in">＋</button><button class="tool" data-action="play-project">▶ Preview arrangement</button></div><div class="timeline-wrap"><div class="ruler">${Array.from({length:16},(_,i)=>`<span>${i+1}</span>`).join('')}</div><div class="lane" id="lane"><span class="lane-label">AUDIO 01</span>${clips.map((c,i)=>{const t=tracks.find(x=>x.id===c.trackId)||tracks[0];return `<div class="clip ${state.selectedClip===c.id?'selected':''}" draggable="true" data-clip="${c.id}" style="left:${c.start*(p.zoom||1)}px;width:${Math.max(90,c.dur*(p.zoom||1))}px"><b>${esc(t.title)}</b><small>${c.start.toFixed(1)}s • ${c.dur.toFixed(1)}s</small><div class="wave">${Array.from({length:24},(_,j)=>`<i style="height:${5+((j*17+i*9)%15)}px"></i>`).join('')}</div></div>`}).join('')}</div><div class="lane"><span class="lane-label">DRUM / FX</span></div><div class="lane"><span class="lane-label">VOCAL / MELODY</span></div></div><div class="automation" id="automation"><div class="tag" style="position:absolute;left:9px;top:7px;z-index:2">VOLUME AUTOMATION</div>${[10,25,40,55,70,85].map(x=>`<i class="gridline" style="left:${x}%"></i>`).join('')}${p.automation.map((a,i)=>`<i class="auto-point" draggable="true" data-auto="${i}" style="left:${a.x}%;top:${a.y}%"></i>`).join('')}</div></div><div class="studio-card"><h3>Selected clip</h3>${clipInspector()}</div></div>`}
function clipInspector(){let c=state.project.clips.find(x=>x.id===state.selectedClip)||state.project.clips[0];if(!c)return `<div class="empty">Select or add a clip.</div>`;let t=tracks.find(x=>x.id===c.trackId)||tracks[0];return `<p class="muted">${esc(t.title)}</p><label>Start <input data-clip-field="start" type="range" min="0" max="120" step="0.1" value="${c.start}"></label><label>Duration <input data-clip-field="dur" type="range" min="1" max="60" step="0.1" value="${c.dur}"></label><label>Gain <input data-clip-field="gain" type="range" min="0" max="1.5" step=".01" value="${c.gain||1}"></label><div class="row"><button class="tool" data-action="duplicate">Duplicate</button><button class="tool" data-action="delete-clip">Delete</button><button class="tool" data-action="audition">▶ Audition</button></div><p class="muted">Beat position: ${beatLabel(c.start)}</p>`}
function beatLabel(sec){const bpm=state.project.bpm||120;const beats=sec*bpm/60;return `beat ${Math.floor(beats)+1} • bar ${Math.floor(beats/4)+1}`}
function mixer(){return `<div class="tag">NEXUS MIXER</div><h2>Per-deck performance</h2><div class="mix-grid">${[1,2,3,4].map(n=>`<div class="deck"><h3>DECK ${n}</h3><p class="muted">${state.project[`deck${n}`]?.title||'Empty slot'}</p><div class="meter">${Array.from({length:18},(_,i)=>`<i style="height:${15+((i*n*13)%60)}%"></i>`).join('')}</div><input class="fader" type="range" min="0" max="1" value="${state.project[`deck${n}`]?.gain||.8}" data-deck="${n}"><div class="row"><button class="tool" data-action="cue" data-deck="${n}">CUE</button><button class="tool" data-action="loop" data-deck="${n}">LOOP 4</button></div></div>`).join('')}</div>`}
function slicer(){return `<div class="tag">SAMPLE SLICER</div><h2>Cut a track into playable moments</h2><p class="muted">Choose a source, then trigger 8 slices. The selected slice can be inserted into the arranger.</p><div class="row"><select id="sliceSource">${tracks.map(t=>`<option value="${t.id}">${esc(t.title)}</option>`).join('')}</select><button class="tool" data-action="slice-auto">Auto-slice</button></div><div class="slices">${Array.from({length:8},(_,i)=>`<button class="slice" data-slice="${i}">${i+1}<small>${i*2} beat</small></button>`).join('')}</div><div class="studio-card" style="margin-top:14px"><h3>Waveform preview</h3><div class="timeline-wrap"><div class="wave" style="height:100px">${Array.from({length:120},(_,i)=>`<i style="height:${8+((i*29)%70)}px"></i>`).join('')}</div></div></div>`}
function projects(){return `<div class="section-head"><div><div class="tag">PROJECTS</div><h2>${esc(state.project.name)}</h2></div><div class="row"><button class="primary" data-action="save">Save JSON</button><button class="secondary" data-action="load">Load JSON</button></div></div><div class="project-list"><div class="project"><span>Autosave</span><strong>${state.autosave?'Enabled':'Ready'}</strong></div><div class="project"><span>BPM</span><strong>${state.project.bpm}</strong></div><div class="project"><span>Clips</span><strong>${state.project.clips.length}</strong></div><div class="project"><span>Automation points</span><strong>${state.project.automation.length}</strong></div></div>`}
function studio(){return `<div class="studio-card"><div class="tag">CREATOR STUDIO</div><h2>V13 tools</h2><div class="cards"><div class="feature"><h3>Arranger</h3><p>Drag, snap, duplicate and automate clips.</p><button class="primary" data-view="arranger">Open</button></div><div class="feature"><h3>Mixer</h3><p>Four performance decks and live controls.</p><button class="primary" data-view="mixer">Open</button></div><div class="feature"><h3>Sample Slicer</h3><p>Turn sections into playable slices.</p><button class="primary" data-view="slicer">Open</button></div></div></div>`}
function filtered(){return tracks.filter(t=>`${t.title} ${t.artist} ${t.genre}`.toLowerCase().includes(state.q.toLowerCase()))}
function render(){const c=$('#content');if(state.view==='home')c.innerHTML=home();else if(state.view==='library')c.innerHTML=library();else if(state.view==='arranger')c.innerHTML=arranger();else if(state.view==='mixer')c.innerHTML=mixer();else if(state.view==='slicer')c.innerHTML=slicer();else if(state.view==='projects')c.innerHTML=projects();else c.innerHTML=studio();$$('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view))}
function selectTrack(id){const t=tracks.find(x=>x.id===id);if(!t)return;state.track=t;state.index=tracks.indexOf(t);audio.src=t.src;audio.load();$('#nowTitle').textContent=t.title;$('#nowArtist').textContent=t.artist;$('#ptitle').textContent=t.title;$('#partist').textContent=t.artist;$('#thumb').textContent='A';$('#art').querySelector('span').textContent=t.title.slice(0,1).toUpperCase();audio.play().then(()=>{state.playing=true;updatePlay()}).catch(()=>{});drawMini()}
function updatePlay(){const s=state.playing?'❚❚':'▶';$('#play').textContent=s;$('#play2').textContent=s}
function toggle(){if(!state.track){selectTrack(tracks[0]);return}if(audio.paused){audio.play();state.playing=true}else{audio.pause();state.playing=false}updatePlay()}
function next(){let i=(state.index+1)%tracks.length;selectTrack(tracks[i].id)}
function prev(){let i=(state.index-1+tracks.length)%tracks.length;selectTrack(tracks[i].id)}
function setupAudio(){audio.addEventListener('timeupdate',()=>{$('#cur').textContent=fmt(audio.currentTime);$('#seek').value=audio.duration?(audio.currentTime/audio.duration)*100:0});audio.addEventListener('loadedmetadata',()=>$('#dur').textContent=fmt(audio.duration));audio.addEventListener('ended',next);audio.addEventListener('play',()=>{state.playing=true;updatePlay();drawMini()});audio.addEventListener('pause',()=>{state.playing=false;updatePlay()});$('#seek').addEventListener('input',e=>{if(audio.duration)audio.currentTime=audio.duration*e.target.value/100});$('#volume').addEventListener('input',e=>audio.volume=e.target.value)}
function drawMini(){const c=$('#miniViz'),x=c.getContext('2d');c.width=c.clientWidth*devicePixelRatio;c.height=c.clientHeight*devicePixelRatio;cancelAnimationFrame(raf);function f(){x.clearRect(0,0,c.width,c.height);for(let i=0;i<35;i++){const h=(8+Math.random()*35)*devicePixelRatio;x.fillStyle=i%3===0?'#fb7185':i%2?'#67e8f9':'#a78bfa';x.fillRect(i*(c.width/35),c.height-h,2*devicePixelRatio,h)}raf=requestAnimationFrame(f)}f()}
function addClip(){const t=state.track||tracks[0];const id=crypto.randomUUID();state.project.clips.push({id,trackId:t.id,start:Math.round((audio.currentTime||0)*2)/2,dur:12,gain:1});state.selectedClip=id;autosave();render()}
function autosave(){state.autosave=true;localStorage.aura13project=JSON.stringify(state.project)}
function saveProject(){const blob=new Blob([JSON.stringify(state.project,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='aura-v13-project.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);toast('Project exported')}
function loadProject(file){const r=new FileReader();r.onload=()=>{try{state.project=JSON.parse(r.result);autosave();render();toast('Project loaded')}catch{toast('Invalid project')}};r.readAsText(file)}
addEventListener('click',e=>{const v=e.target.closest('[data-view]'),a=e.target.closest('[data-action]'),t=e.target.closest('[data-track]'),s=e.target.closest('[data-slice]');if(v){state.view=v.dataset.view;render();return}if(t){selectTrack(t.dataset.track);return}if(s){s.classList.add('hit');setTimeout(()=>s.classList.remove('hit'),180);toast(`Slice ${Number(s.dataset.slice)+1} triggered`);return}if(!a)return;const act=a.dataset.action;if(act==='play')toggle();else if(act==='next')next();else if(act==='prev')prev();else if(act==='import')$('#files').click();else if(act==='menu')$('#sidebar').classList.toggle('open');else if(act==='theme'){document.body.classList.toggle('light');state.theme=document.body.classList.contains('light')?'light':'dark';localStorage.aura13theme=state.theme}else if(act==='play-all'){selectTrack(filtered()[0]?.id||tracks[0].id)}else if(act==='add-clip')addClip();else if(act==='save')saveProject();else if(act==='load')$('#projectFile').click();else if(act==='snap'){state.project.snap=!state.project.snap;render()}else if(act==='duplicate'){const c=state.project.clips.find(x=>x.id===state.selectedClip);if(c){const n={...c,id:crypto.randomUUID(),start:c.start+c.dur};state.project.clips.push(n);state.selectedClip=n.id;autosave();render()}}else if(act==='delete-clip'){state.project.clips=state.project.clips.filter(x=>x.id!==state.selectedClip);state.selectedClip=null;autosave();render()}else if(act==='audition'){const c=state.project.clips.find(x=>x.id===state.selectedClip);if(c){const t=tracks.find(x=>x.id===c.trackId);selectTrack(t.id);setTimeout(()=>audio.currentTime=0,50)}}else if(act==='zoom-in'){state.project.zoom=Math.min(2,(state.project.zoom||1)+.2);render()}else if(act==='zoom-out'){state.project.zoom=Math.max(.5,(state.project.zoom||1)-.2);render()}else if(act==='play-project'){const c=state.project.clips[0];if(c){const t=tracks.find(x=>x.id===c.trackId)||tracks[0];selectTrack(t.id);setTimeout(()=>audio.currentTime=c.start,80)}}else if(act==='slice-auto')toast('8 slices mapped to the selected source')} );
$('#search').addEventListener('input',e=>{state.q=e.target.value;render()});$('#files').addEventListener('change',e=>{[...e.target.files].forEach(f=>{const u=URL.createObjectURL(f);tracks.push({id:crypto.randomUUID(),title:f.name.replace(/\.[^.]+$/,''),artist:'Local import',genre:'Imported',src:u})});render();toast(`${e.target.files.length} track(s) added`) });$('#projectFile').addEventListener('change',e=>e.target.files[0]&&loadProject(e.target.files[0]));
addEventListener('dragstart',e=>{const c=e.target.closest('.clip');if(c)e.dataTransfer.setData('text/plain',c.dataset.clip)});addEventListener('dragend',e=>{const c=e.target.closest('.clip');if(c){const r=c.parentElement.getBoundingClientRect();const x=Math.max(0,e.clientX-r.left);const z=state.project.zoom||1;const item=state.project.clips.find(q=>q.id===c.dataset.clip);if(item){item.start=state.project.snap?Math.round((x/z)/(60/state.project.bpm)*4)/4:x/z;state.selectedClip=item.id;autosave();render()}}});
addEventListener('input',e=>{const f=e.target.dataset.clipField;if(f){const c=state.project.clips.find(x=>x.id===state.selectedClip);if(c){c[f]=Number(e.target.value);autosave();render()}}const d=e.target.dataset.deck;if(d){state.project[`deck${d}`]={...(state.project[`deck${d}`]||{}),gain:Number(e.target.value)};autosave()}});
addEventListener('dblclick',e=>{const box=e.target.closest('#automation');if(!box)return;const r=box.getBoundingClientRect();state.project.automation.push({x:Math.max(0,Math.min(100,(e.clientX-r.left)/r.width*100)),y:Math.max(0,Math.min(100,(e.clientY-r.top)/r.height*100))});autosave();render()});
addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#search').focus()}if(e.code==='Space'&&document.activeElement.tagName!=='INPUT'){e.preventDefault();toggle()}if(e.key.toLowerCase()==='n')next()});
(function init(){document.body.classList.toggle('light',state.theme==='light');state.project.snap=true;state.project.zoom=1;try{const p=localStorage.aura13project;if(p)state.project=JSON.parse(p)}catch{}setupAudio();render();audio.volume=.85;$('#status').textContent='Local • autosave ready';})();
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});

/* ================= V14 NEXUS PRO ================= */
state.v14 = { crossfade:50, master:1, fx:{low:0,mid:0,high:0,space:25,echo:0}, history:[], selectedCue:0 };
const _v14_renderOrig = render;
function v14Render(){
  _v14_renderOrig();
  if(state.view==='protools') initV14Tools();
}
render=v14Render;
function protTools(){return `<div class="section-head"><div><span class="badge-pro">V14 • NEXUS PRO</span><h2>Performance & Sound Lab</h2><p class="muted">Waveform control, transition mixing, cue memory and master effects — all local.</p></div><div class="row"><button class="tool" data-action="v14-undo">↶ Undo</button><button class="tool" data-action="v14-reset">Reset</button><button class="primary" data-action="v14-save">Save snapshot</button></div></div><div class="pro-grid"><div class="pro-card"><h3>Live Waveform</h3><div class="wave-editor"><canvas id="v14Wave"></canvas><div class="playhead" id="v14Playhead"></div></div><div class="row" style="margin-top:10px"><button class="tool" data-action="v14-jump" data-sec="0">Intro</button><button class="tool" data-action="v14-jump" data-sec="15">Build</button><button class="tool" data-action="v14-jump" data-sec="30">Drop</button><button class="tool" data-action="v14-jump" data-sec="45">Outro</button></div><h3 style="margin-top:18px">A ↔ B Crossfader</h3><div class="crossfade"><input id="v14Cross" type="range" min="0" max="100" value="${state.v14.crossfade}"></div><div class="row"><span class="pill">Deck A ${100-state.v14.crossfade}%</span><span class="pill">Deck B ${state.v14.crossfade}%</span></div></div><div class="pro-card"><h3>Master FX Rack</h3><div class="fx-grid">${[['low','Low',-12,12],['mid','Mid',-12,12],['high','Air',-12,12],['space','Space',0,100],['echo','Echo',0,100],['master','Master',0,1.5]].map(([k,n,min,max])=>`<div class="fx-control"><label>${n}<b id="v14-${k}-val">${state.v14[k==='master'?'master':'fx'][k==='master'?'master':k]}</b></label><input data-v14-fx="${k}" type="range" min="${min}" max="${max}" step=".01" value="${state.v14[k==='master'?'master':'fx'][k==='master'?'master':k]}"></div>`).join('')}</div><h3 style="margin-top:18px">Cue Matrix</h3><div class="cue-grid">${Array.from({length:16},(_,i)=>`<button class="cue" data-action="v14-cue" data-cue="${i}">${String(i+1).padStart(2,'0')}</button>`).join('')}</div><h3 style="margin-top:18px">Snapshots</h3><div class="history" id="v14History">${state.v14.history.map((h,i)=>`<button data-action="v14-load" data-h="${i}">${esc(h.name)} • ${h.time}</button>`).join('')||'<span class="muted">No snapshots yet.</span>'}</div></div></div>`}
const _oldViews = {protools: protTools};
const _viewOrig = window.view;
if(typeof window.view==='function'){ /* compatibility */ }
// Patch render output by wrapping content source through view resolver.
const _content = $('#content');
const _originalRender = render;
render=function(){
  if(state.view==='protools'){$('#content').innerHTML=protTools(); bind(); if(state.track) updateUI(); initV14Tools(); return;}
  _originalRender();
};
function initV14Tools(){
 const c=$('#v14Wave'); if(!c)return; const dpr=devicePixelRatio||1, r=c.getBoundingClientRect(); c.width=r.width*dpr;c.height=r.height*dpr;const x=c.getContext('2d');x.scale(dpr,dpr);x.clearRect(0,0,r.width,r.height);x.strokeStyle='#2d3348';x.lineWidth=1;for(let i=0;i<12;i++){let y=i*r.height/12;x.beginPath();x.moveTo(0,y);x.lineTo(r.width,y);x.stroke()}x.strokeStyle='#67e8f9';x.lineWidth=1.4;x.beginPath();for(let i=0;i<r.width;i++){let v=Math.sin(i*.06)*.22+Math.sin(i*.17)*.12+Math.sin(i*.41)*.08;let y=r.height/2+v*r.height*.8;if(i===0)x.moveTo(i,y);else x.lineTo(i,y)}x.stroke();x.strokeStyle='#a78bfa';x.beginPath();for(let i=0;i<r.width;i++){let v=Math.sin(i*.12)*.14+Math.sin(i*.33)*.06;let y=r.height/2+v*r.height*.65;if(i===0)x.moveTo(i,y);else x.lineTo(i,y)}x.stroke();
 const cf=$('#v14Cross');if(cf)cf.oninput=e=>{state.v14.crossfade=+e.target.value;saveV14Local();render();};
 $$('[data-v14-fx]').forEach(el=>el.oninput=e=>{const k=e.target.dataset.v14Fx;if(k==='master')state.v14.master=+e.target.value;else state.v14.fx[k]=+e.target.value; const out=$(`#v14-${k}-val`);if(out)out.textContent=e.target.value; applyV14Fx();saveV14Local();});
}
function applyV14Fx(){try{if(gain)gain.gain.value=Math.max(0,Math.min(1.5,state.v14.master));}catch(e){}}
function saveV14Local(){localStorage.aura14=JSON.stringify(state.v14)}
try{if(localStorage.aura14)Object.assign(state.v14,JSON.parse(localStorage.aura14))}catch(e){}
const _bindOrig=bind;
bind=function(){_bindOrig();$$('[data-action="v14-cue"]').forEach(b=>b.onclick=()=>{const i=+b.dataset.cue;state.v14.selectedCue=i;const sec=(i%8)*8; if(audio.duration)audio.currentTime=Math.min(sec,audio.duration-0.05);b.classList.add('hit');setTimeout(()=>b.classList.remove('hit'),120);toast(`Cue ${i+1} triggered`);});$$('[data-action="v14-jump"]').forEach(b=>b.onclick=()=>{const sec=+b.dataset.sec;if(audio.duration)audio.currentTime=Math.min(sec,audio.duration-0.05);toast(`Jumped to ${b.textContent}`)});$$('[data-action="v14-reset"]').forEach(b=>b.onclick=()=>{state.v14={crossfade:50,master:1,fx:{low:0,mid:0,high:0,space:25,echo:0},history:[],selectedCue:0};saveV14Local();render()});$$('[data-action="v14-save"]').forEach(b=>b.onclick=()=>{state.v14.history.unshift({name:state.track?state.track.title:'AURA Snapshot',time:new Date().toLocaleTimeString()});state.v14.history=state.v14.history.slice(0,8);saveV14Local();render();toast('Snapshot saved')});$$('[data-action="v14-load"]').forEach(b=>b.onclick=()=>{toast('Snapshot recalled')});$$('[data-action="v14-undo"]').forEach(b=>b.onclick=()=>toast('Undo ready for the next edit'));};


/* ================= V15 QUANTUM CREATOR STUDIO ================= */
// V15 drops the wallpaper layer and focuses on deeper music creation tools.
if(typeof bind==='undefined') window.bind=function(){};
const v15={
  tab:'editor', start:0, end:0, fadeIn:.25, fadeOut:.35, gain:1, pan:0,
  loop:false, loopStart:0, loopEnd:8, snap:true, bpm:120,
  eq:{low:0,mid:0,high:0}, space:0, echo:0, master:1,
  automation:[{x:0,y:70},{x:28,y:45},{x:58,y:78},{x:100,y:55}],
  snapshots:[], waveform:null, history:[]
};
try{Object.assign(v15,JSON.parse(localStorage.aura15quantum||'{}'))}catch(e){}
function saveV15(){localStorage.aura15quantum=JSON.stringify({...v15,waveform:null});}
function v15Track(){return state.track||tracks[0]}
function v15Time(v){return Number.isFinite(v)?Math.max(0,v):0}
function v15Clamp(v,a,b){return Math.min(b,Math.max(a,v))}
function v15EnsureGraph(){
  if(ctx)return;
  try{
    ctx=new (window.AudioContext||window.webkitAudioContext)();
    source=ctx.createMediaElementSource(audio);
    const low=ctx.createBiquadFilter(); low.type='lowshelf'; low.frequency.value=180;
    const mid=ctx.createBiquadFilter(); mid.type='peaking'; mid.frequency.value=1000; mid.Q.value=.8;
    const high=ctx.createBiquadFilter(); high.type='highshelf'; high.frequency.value=5200;
    const pan=ctx.createStereoPanner();
    const delay=ctx.createDelay(1.5); const fb=ctx.createGain(); fb.gain.value=0;
    gain=ctx.createGain(); analyser=ctx.createAnalyser(); analyser.fftSize=1024;
    source.connect(low).connect(mid).connect(high).connect(pan).connect(gain).connect(analyser).connect(ctx.destination);
    delay.delayTime.value=.24; delay.connect(fb).connect(delay); delay.connect(gain);
    v15._nodes={low,mid,high,pan,delay,fb,gain};
    applyV15FX();
  }catch(e){toast('Audio FX unavailable in this browser')}
}
function applyV15FX(){
  if(!v15._nodes)return;
  const n=v15._nodes;
  n.low.gain.value=v15.eq.low; n.mid.gain.value=v15.eq.mid; n.high.gain.value=v15.eq.high;
  n.pan.pan.value=v15.pan; n.gain.gain.value=v15.master*v15.gain;
  n.fb.gain.value=Math.min(.78,v15.echo/140);
  n.delay.delayTime.value=.12+v15.echo/500;
}
function v15WaveUI(){
  const t=v15Track();
  return `<div class="q-card q-wave-card"><div class="q-card-head"><div><span class="tag">WAVEFORM EDITOR</span><h3>${esc(t.title)}</h3><p class="muted">Click to seek • drag region handles • export a new WAV without changing the source.</p></div><div class="q-actions"><button class="tool" data-action="v15-refresh-wave">↻ Refresh</button><button class="primary" data-action="v15-render">Render WAV</button></div></div><div class="q-wave"><canvas id="v15Wave"></canvas><div class="q-playhead" id="v15Head"></div><div class="q-region" id="v15Region"><span class="q-handle left" data-handle="start"></span><span class="q-handle right" data-handle="end"></span></div></div><div class="q-scale"><span>0:00</span><span id="qWaveDur">—</span></div></div>`;
}
function v15EditorPanel(){
  const t=v15Track();
  const dur=audio.duration||60;
  if(!v15.end||v15.end>dur)v15.end=dur;
  if(v15.start>v15.end-.05)v15.start=Math.max(0,v15.end-.05);
  return `<div class="q-card"><div class="q-card-head"><div><span class="tag">NON-DESTRUCTIVE EDIT</span><h3>Region & Tone</h3></div><span class="q-badge">SOURCE SAFE</span></div>
  <div class="q-grid-2"><label>Start <output id="qStartVal">${fmt(v15.start)}</output><input data-v15="start" type="range" min="0" max="${dur}" step=".01" value="${v15.start}"></label><label>End <output id="qEndVal">${fmt(v15.end)}</output><input data-v15="end" type="range" min="0" max="${dur}" step=".01" value="${v15.end}"></label><label>Fade in <output>${v15.fadeIn.toFixed(2)}s</output><input data-v15="fadeIn" type="range" min="0" max="5" step=".05" value="${v15.fadeIn}"></label><label>Fade out <output>${v15.fadeOut.toFixed(2)}s</output><input data-v15="fadeOut" type="range" min="0" max="5" step=".05" value="${v15.fadeOut}"></label><label>Gain <output>${v15.gain.toFixed(2)}×</output><input data-v15="gain" type="range" min="0" max="1.5" step=".01" value="${v15.gain}"></label><label>Pan <output>${v15.pan>0?'+':''}${Math.round(v15.pan*100)}</output><input data-v15="pan" type="range" min="-1" max="1" step=".01" value="${v15.pan}"></label></div>
  <div class="q-row"><button class="tool" data-action="v15-set-start">Set start @ playhead</button><button class="tool" data-action="v15-set-end">Set end @ playhead</button><button class="tool" data-action="v15-reset-region">Reset region</button><button class="tool" data-action="v15-preview-region">▶ Preview</button></div>
  <p class="muted q-note">Editing is non-destructive. Render WAV creates a new file from the selected region.</p></div>`;
}
function v15FXPanel(){
  const fx=[['low','Low',-12,12],['mid','Mid',-12,12],['high','Air',-12,12]];
  return `<div class="q-card"><div class="q-card-head"><div><span class="tag">LIVE FX CHAIN</span><h3>Sound shaping</h3></div><button class="tool" data-action="v15-fx-reset">Reset FX</button></div><div class="q-fx-grid">${fx.map(([k,n,min,max])=>`<label>${n}<output>${v15.eq[k]} dB</output><input data-v15fx="${k}" type="range" min="${min}" max="${max}" step=".1" value="${v15.eq[k]}"></label>`).join('')}<label>Space<output>${Math.round(v15.space)}%</output><input data-v15fx="space" type="range" min="0" max="100" value="${v15.space}"></label><label>Echo<output>${Math.round(v15.echo)}%</output><input data-v15fx="echo" type="range" min="0" max="100" value="${v15.echo}"></label><label>Master<output>${v15.master.toFixed(2)}×</output><input data-v15fx="master" type="range" min="0" max="1.5" step=".01" value="${v15.master}"></label></div><div class="q-meter"><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span></div></div>`;
}
function v15AutomationPanel(){return `<div class="q-card"><div class="q-card-head"><div><span class="tag">AUTOMATION</span><h3>Master volume curve</h3></div><button class="tool" data-action="v15-auto-clear">Clear</button></div><div class="q-auto" id="v15Auto">${[20,40,60,80].map(x=>`<i class="q-grid" style="left:${x}%"></i>`).join('')}${v15.automation.map((p,i)=>`<i class="q-auto-point" draggable="true" data-auto15="${i}" style="left:${p.x}%;top:${p.y}%"></i>`).join('')}</div><p class="muted">Double-click to add points. Drag points to shape the curve.</p></div>`}
function v15Transport(){const t=v15Track();return `<div class="q-transport"><div><strong>${esc(t.title)}</strong><span>${esc(t.artist)} • ${esc(t.genre)}</span></div><div class="q-transport-buttons"><button class="tool" data-action="v15-prev">◀</button><button class="primary" data-action="play">${state.playing?'❚❚':'▶'}</button><button class="tool" data-action="v15-next">▶</button><button class="tool ${v15.loop?'is-on':''}" data-action="v15-loop">↻ Loop</button></div><div class="q-bpm"><label>BPM <input id="v15Bpm" type="number" min="40" max="240" value="${v15.bpm}"></label><label><input id="v15Snap" type="checkbox" ${v15.snap?'checked':''}> Beat snap</label></div></div>`}
function v15Snapshots(){return `<div class="q-card"><div class="q-card-head"><div><span class="tag">PROJECT MEMORY</span><h3>Snapshots & recovery</h3></div><button class="primary" data-action="v15-snapshot">Save snapshot</button></div><div class="q-snapshots">${v15.snapshots.map((s,i)=>`<button data-action="v15-load-snapshot" data-snap="${i}"><b>${esc(s.name)}</b><span>${esc(s.time)}</span></button>`).join('')||'<span class="muted">No snapshots yet.</span>'}</div></div>`}
function quantumTools(){return `<div class="q-shell"><div class="q-head"><div><span class="badge-pro">V15 • QUANTUM CREATOR</span><h2>Professional Music Lab</h2><p class="muted">Edit, shape, arrange and render locally — with the original track kept untouched.</p></div><div class="q-head-actions"><button class="tool" data-action="v15-undo">↶ Undo</button><button class="tool" data-action="v15-save-project">💾 Project</button></div></div>${v15Transport()}<div class="q-tabs"><button class="${v15.tab==='editor'?'active':''}" data-qtab="editor">Editor</button><button class="${v15.tab==='mix'?'active':''}" data-qtab="mix">Mixer</button><button class="${v15.tab==='automation'?'active':''}" data-qtab="automation">Automation</button><button class="${v15.tab==='memory'?'active':''}" data-qtab="memory">Snapshots</button></div>${v15.tab==='editor'?`<div class="q-layout"><div>${v15WaveUI()}${v15EditorPanel()}</div><div>${v15FXPanel()}${v15AutomationPanel()}</div></div>`:''}${v15.tab==='mix'?v15MixPanel():''}${v15.tab==='automation'?`<div class="q-layout single">${v15AutomationPanel()}${v15FXPanel()}</div>`:''}${v15.tab==='memory'?`<div class="q-layout single">${v15Snapshots()}<div class="q-card"><div class="q-card-head"><div><span class="tag">EXPORT</span><h3>Creative delivery</h3></div></div><div class="q-export-grid"><button class="primary" data-action="v15-render">Render selected WAV</button><button class="tool" data-action="v15-export-project">Export project JSON</button><button class="tool" data-action="v15-load-project">Import project JSON</button></div><p class="muted">Exports are generated in your browser. No cloud upload is required.</p></div></div>`:''}</div>`}
function v15MixPanel(){return `<div class="q-layout"><div class="q-card"><div class="q-card-head"><div><span class="tag">PERFORMANCE MIXER</span><h3>A / B transition</h3></div></div><div class="q-cross"><span>A</span><input id="v15Cross" type="range" min="0" max="100" value="${state.v14?.crossfade||50}"><span>B</span></div><div class="q-decks">${['A','B','C','D'].map((d,i)=>`<div class="q-deck"><span>DECK ${d}</span><select data-qdeck="${d}">${tracks.map(t=>`<option value="${t.id}" ${((v15.decks||{})[d]===t.id||(i===0&&d==='A'&&!v15.decks))?'selected':''}>${esc(t.title)}</option>`).join('')}</select><input data-qgain="${d}" type="range" min="0" max="1.2" step=".01" value="${((v15.gains||{})[d]??.85)}"><div class="q-mini-meter">${Array.from({length:14},(_,j)=>`i`).map((_,j)=>`<b style="height:${18+((j*(i+3)*11)%62)}%"></b>`).join('')}</div></div>`).join('')}</div></div><div class="q-card"><span class="tag">PERFORMANCE NOTES</span><h3>Transition tools</h3><div class="q-preset-grid"><button data-action="v15-transition" data-kind="clean">Clean cut</button><button data-action="v15-transition" data-kind="fade">Smooth fade</button><button data-action="v15-transition" data-kind="echo">Echo out</button><button data-action="v15-transition" data-kind="drop">Drop swap</button></div><p class="muted">Presets update the local performance state; the current player remains the playback source.</p></div></div>`}
async function v15Decode(src){
  const res=await fetch(src); const buf=await res.arrayBuffer(); const ac=new (window.AudioContext||window.webkitAudioContext)(); try{return await ac.decodeAudioData(buf)}finally{setTimeout(()=>ac.close(),0)}
}
async function v15DrawWave(){
  const c=$('#v15Wave'); if(!c)return;
  const r=c.getBoundingClientRect(),dpr=devicePixelRatio||1;c.width=Math.max(1,r.width*dpr);c.height=Math.max(1,r.height*dpr);const x=c.getContext('2d');x.setTransform(dpr,0,0,dpr,0,0);x.clearRect(0,0,r.width,r.height);
  x.fillStyle='rgba(7,10,20,.35)';x.fillRect(0,0,r.width,r.height);
  try{
    if(!v15.waveform||v15.waveform.src!==v15Track().src){const b=await v15Decode(v15Track().src);const data=b.getChannelData(0);const points=900;const arr=new Float32Array(points);const step=Math.max(1,Math.floor(data.length/points));for(let i=0;i<points;i++){let m=0;for(let j=0;j<step&&i*step+j<data.length;j++)m=Math.max(m,Math.abs(data[i*step+j]));arr[i]=m}v15.waveform={src:v15Track().src,data:Array.from(arr),duration:b.duration};}
    const a=v15.waveform.data; x.strokeStyle='#8b5cf6';x.lineWidth=1.5;x.beginPath();for(let i=0;i<a.length;i++){const px=i/(a.length-1)*r.width,py=r.height/2-a[i]*r.height*.42;i?x.lineTo(px,py):x.moveTo(px,py)}x.stroke();x.strokeStyle='#67e8f9';x.globalAlpha=.55;x.beginPath();for(let i=0;i<a.length;i++){const px=i/(a.length-1)*r.width,py=r.height/2+a[i]*r.height*.42;i?x.lineTo(px,py):x.moveTo(px,py)}x.stroke();x.globalAlpha=1;
    $('#qWaveDur').textContent=fmt(v15.waveform.duration);v15UpdateRegion();
  }catch(e){x.fillStyle='#9ca3af';x.font='13px sans-serif';x.fillText('Waveform preview unavailable — playback still works.',18,r.height/2)}
}
function v15UpdateRegion(){const c=$('#v15Wave'),reg=$('#v15Region'),head=$('#v15Head');if(!c||!reg)return;const dur=v15.waveform?.duration||audio.duration||1;const left=v15.start/dur*100,right=100-v15.end/dur*100;reg.style.left=left+'%';reg.style.right=right+'%';head.style.left=((audio.currentTime||0)/dur*100)+'%';}
function v15BindTools(){
  v15EnsureGraph();
  $$('[data-qtab]').forEach(b=>b.onclick=()=>{v15.tab=b.dataset.qtab;saveV15();render()});
  $$('[data-v15]').forEach(el=>el.oninput=()=>{const k=el.dataset.v15;v15[k]=Number(el.value);if(k==='start')v15.start=v15Clamp(v15.start,0,(v15.end||audio.duration||60)-.05);if(k==='end')v15.end=v15Clamp(v15.end,v15.start+.05,audio.duration||v15.end);saveV15();render()});
  $$('[data-v15fx]').forEach(el=>el.oninput=()=>{const k=el.dataset.v15fx;if(k==='low'||k==='mid'||k==='high')v15.eq[k]=Number(el.value);else v15[k]=Number(el.value);applyV15FX();saveV15();const o=el.parentElement.querySelector('output');if(o)o.textContent=k==='master'?v15.master.toFixed(2)+'×':(k==='low'||k==='mid'||k==='high'?v15.eq[k]+' dB':Math.round(v15[k])+'%')});
  const bpm=$('#v15Bpm');if(bpm)bpm.oninput=()=>{v15.bpm=Number(bpm.value)||120;state.project.bpm=v15.bpm;saveV15()};const snap=$('#v15Snap');if(snap)snap.onchange=()=>{v15.snap=snap.checked;saveV15()};
  const cross=$('#v15Cross');if(cross)cross.oninput=()=>{state.v14=state.v14||{};state.v14.crossfade=Number(cross.value);saveV15()};
  $$('[data-qdeck]').forEach(s=>s.onchange=()=>{v15.decks=v15.decks||{};v15.decks[s.dataset.qdeck]=s.value;saveV15()});
  $$('[data-qgain]').forEach(s=>s.oninput=()=>{v15.gains=v15.gains||{};v15.gains[s.dataset.qgain]=Number(s.value);saveV15()});
  v15DrawWave();
  audio.addEventListener('timeupdate',v15UpdateRegion,{once:true});
}
async function v15RenderWav(){
  const t=v15Track(); toast('Rendering WAV…');
  try{
    const b=await v15Decode(t.src);const start=v15Clamp(v15.start,0,b.duration);const end=v15Clamp(v15.end,start+.01,b.duration);const dur=end-start;const off=new OfflineAudioContext(b.numberOfChannels,b.sampleRate*Math.ceil(dur),b.sampleRate);const src=off.createBufferSource();src.buffer=b;const g=off.createGain();const p=off.createStereoPanner?v15Clamp(v15.pan,-1,1):null;let node=g;if(p){src.connect(g);g.connect(p);node=p}else src.connect(g);node.connect(off.destination);g.gain.setValueAtTime(0,0);const fi=Math.min(v15.fadeIn,dur/2),fo=Math.min(v15.fadeOut,dur/2);g.gain.linearRampToValueAtTime(v15.gain,fi);g.gain.setValueAtTime(v15.gain,Math.max(fi,dur-fo));g.gain.linearRampToValueAtTime(0,dur);src.start(0,start,dur);const out=await off.startRendering();const wav=v15EncodeWav(out);const blob=new Blob([wav],{type:'audio/wav'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`AURA-${t.title.replace(/[^a-z0-9]+/gi,'-')}-edit.wav`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500);toast('WAV rendered successfully');
  }catch(e){console.error(e);toast('Render failed — try a bundled/local track')}
}
function v15EncodeWav(buffer){const ch=buffer.numberOfChannels,len=buffer.length,rate=buffer.sampleRate,block=ch*2,dataSize=len*block;const ab=new ArrayBuffer(44+dataSize),v=new DataView(ab);const ws=(o,s)=>{for(let i=0;i<s.length;i++)v.setUint8(o+i,s.charCodeAt(i))};ws(0,'RIFF');v.setUint32(4,36+dataSize,true);ws(8,'WAVE');ws(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,ch,true);v.setUint32(24,rate,true);v.setUint32(28,rate*block,true);v.setUint16(32,block,true);v.setUint16(34,16,true);ws(36,'data');v.setUint32(40,dataSize,true);let o=44;for(let i=0;i<len;i++)for(let c=0;c<ch;c++){let s=Math.max(-1,Math.min(1,buffer.getChannelData(c)[i]));v.setInt16(o,s<0?s*0x8000:s*0x7fff,true);o+=2}return ab}
function v15Snapshot(){v15.snapshots.unshift({name:state.track?state.track.title:'AURA Project',time:new Date().toLocaleTimeString(),data:JSON.parse(JSON.stringify({...v15,waveform:null}))});v15.snapshots=v15.snapshots.slice(0,8);saveV15();render();toast('Snapshot saved')}
const oldRenderV15=render;
render=function(){if(state.view==='protools'){$('#content').innerHTML=quantumTools();v15BindTools();return}oldRenderV15()};
addEventListener('click',e=>{
 const a=e.target.closest('[data-action]');
 if(a){const act=a.dataset.action;
  if(act==='v15-render')v15RenderWav();
  else if(act==='v15-refresh-wave'){v15.waveform=null;v15DrawWave()}
  else if(act==='v15-set-start'){v15.start=v15Clamp(audio.currentTime,0,Math.max(.01,(v15.end||audio.duration)-.05));saveV15();render()}
  else if(act==='v15-set-end'){v15.end=v15Clamp(audio.currentTime,(v15.start||0)+.05,audio.duration||audio.currentTime+.05);saveV15();render()}
  else if(act==='v15-reset-region'){v15.start=0;v15.end=audio.duration||v15.waveform?.duration||60;v15.fadeIn=.25;v15.fadeOut=.35;saveV15();render()}
  else if(act==='v15-preview-region'){if(audio.duration){audio.currentTime=v15.start;audio.play();state.playing=true;updatePlay();}}
  else if(act==='v15-loop'){v15.loop=!v15.loop;saveV15();render()}
  else if(act==='v15-prev')prev();
  else if(act==='v15-next')next();
  else if(act==='v15-fx-reset'){v15.eq={low:0,mid:0,high:0};v15.space=0;v15.echo=0;v15.master=1;applyV15FX();saveV15();render()}
  else if(act==='v15-auto-clear'){v15.automation=[];saveV15();render()}
  else if(act==='v15-snapshot')v15Snapshot();
  else if(act==='v15-load-snapshot'){const s=v15.snapshots[Number(a.dataset.snap)];if(s){Object.assign(v15,s.data);saveV15();applyV15FX();render();toast('Snapshot recalled')}}
  else if(act==='v15-save-project')saveProject();
  else if(act==='v15-export-project')saveProject();
  else if(act==='v15-load-project')$('#projectFile').click();
  else if(act==='v15-transition'){const k=a.dataset.kind;if(k==='echo')v15.echo=65;if(k==='fade')v15.space=20;if(k==='drop')v15.master=.95;if(k==='clean'){v15.echo=0;v15.space=0}applyV15FX();saveV15();toast(`${k} transition preset applied`);render()}
 }
 const h=e.target.closest('#v15Wave');if(h){const r=h.getBoundingClientRect(),pct=v15Clamp((e.clientX-r.left)/r.width,0,1),dur=v15.waveform?.duration||audio.duration||0;if(dur)audio.currentTime=pct*dur}
});
addEventListener('dblclick',e=>{const box=e.target.closest('#v15Auto');if(!box)return;const r=box.getBoundingClientRect();v15.automation.push({x:v15Clamp((e.clientX-r.left)/r.width*100,0,100),y:v15Clamp((e.clientY-r.top)/r.height*100,0,100)});v15.automation.sort((a,b)=>a.x-b.x);saveV15();render()});
addEventListener('pointerdown',e=>{const p=e.target.closest('.q-auto-point');if(!p)return;const idx=Number(p.dataset.auto15),box=p.parentElement;const move=ev=>{const r=box.getBoundingClientRect();v15.automation[idx]={x:v15Clamp((ev.clientX-r.left)/r.width*100,0,100),y:v15Clamp((ev.clientY-r.top)/r.height*100,0,100)};p.style.left=v15.automation[idx].x+'%';p.style.top=v15.automation[idx].y+'%'};const up=()=>{removeEventListener('pointermove',move);removeEventListener('pointerup',up);saveV15()};addEventListener('pointermove',move);addEventListener('pointerup',up)});
audio.addEventListener('timeupdate',()=>{if(v15.loop&&audio.currentTime>=v15.loopEnd&&v15.loopEnd>v15.loopStart){audio.currentTime=v15.loopStart;audio.play().catch(()=>{})}if(state.view==='protools')v15UpdateRegion()});
